### ISSUE TITLE
Broken on node v0.12.0

### ISSUE THREAD

**Issue by gabrielstuff** [TheThingSystem/node-arp-a#3]
Unfortunately it looks broken on last version. Node-gyp can't build it.

Anyway thanks for this module which run with v0.10.35

**Comment by mrose17** [comment]
i guess i need to fix it then! thanks.

**Comment by mrose17** [comment]
fixed by https://github.com/TheThingSystem/node-arp-a/commit/c77e488d3dc4eec21193753c0ec12832e6002108 ... sorry for the (very long) delay!

use arp-a@0.5.0
