### ISSUE TITLE
Promise support?

### ISSUE THREAD

**Issue by menixator** [TheThingSystem/node-arp-a#6]
I just want to start out by saying that I completely agree with you when you say that parsing programmatic is unreliable. I had to check out the source code of the other module to find out that it uses the `arp` command and searched again to find this. Thanks for making this. As someone who's starting out with CCNA, this is a great module to play around with. :+1: 

Now for the real question: Would you consider adding promise support for this module? Since it's quickly becoming the new standard, it wouldn't hurt to support it.

You can just modify it to return a promise if `Promise` is globally defined. Would be pretty neat if you did :smile:

**Comment by mrose17** [comment]
sure. point me to an example in another package and i can do that...

**Comment by mrose17** [comment]
@menixator ^^^

**Comment by mrose17** [comment]
closed due to lack of response.
